### ISSUE TITLE
If statement in get_ltGRN is opposite

### ISSUE THREAD

**Issue by sdettle** [ChanghanGitHub/exFINDER#2]
if (length(T.diff) == 0) {
    warning("The following target genes have been ignored: ", T.diff ,"\n")}
should be 
  if (length(T.diff) != 0) {
    warning("The following target genes have been ignored: ", T.diff ,"\n")}

Since T.diff is only >1 when there is a gene that is in the targets that is not in the Layer3.to genes

**Comment by ChanghanGitHub** [comment]
Hi sdettle,

The typo has been fixed, thank you for pointing this out!

Best,
Changhan
